image:
  name: google/cloud-sdk
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - apt-get install -qqy unzip
  - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
  - unzip terraform_0.11.11_linux_amd64.zip
  - sudo install terraform /usr/local/bin/
  - terraform --version
  - mkdir -p ~/.gcp
  - echo $GCPCRED | base64 -d > ~/.gcp/k8s-hybrid-cloud-0f1ceb09cf2a.json
  - terraform init

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false -auto-approve "planfile"
  dependencies:
    - plan
  artifacts:
    paths:
      - terraform.tfstate
    when: always
  when: manual
  
destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  dependencies:
    - apply
  artifacts:
    paths:
      - terraform.tfstate
      - terraform.tfstate.backup
    when: always
  when: manual